backend:
  name: git-gateway
  branch: main

media_library:
  name: cloudinary
  config:
    cloud_name: dugnmvbnv
    api_key: 573995755218881
    upload_preset: Root-moto
    folder: moto-trips

collections:
  - name: trips
    label: Trips
    folder: src/content/trips
    path: "{{slug}}/index"
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: End Date, name: date_end, widget: datetime, format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false, required: false }
      - { label: Description, name: description, widget: text }
      - { label: Distance (km), name: distance, widget: number, required: false }
      - { label: Elevation (m), name: elevation, widget: number, required: false }
      - { label: YouTube Video ID, name: youtube, widget: string, required: false }
      - label: Photos
        name: photos
        widget: list
        required: false
        field:
          label: Photo
          name: photo
          widget: image
          media_folder: /public/uploads
          public_folder: /uploads
      - { label: Body, name: body, widget: markdown }